"""SQLAlchemy declarative base + reusable column mixins.

This module is **mechanical scaffolding** — it codifies the conventions
already documented in `docs/architecture/data-model.md`. It does not
declare any table; the actual schema lands per module:

- `id_*` tables in `openspine.identity` (v0.1 §4.2)
- `md_*` tables in `openspine.md` (v0.1 §4.4)
- `fin_*` / `co_*` tables in `openspine.fi` and `openspine.co` (v0.2)
- `mm_*` tables in `openspine.mm` (v0.3)
- `pp_*` tables in `openspine.pp` (v0.4)

Every business table inherits from `Base` and mixes in `BusinessTableMixin`
(or `AuditMixin` for the few documented globals that don't carry a
`tenant_id`).

The strategic schema decisions — column types per entity, RLS policy
shape, audit-trigger pattern, agent-token shape — are reserved for the
council per the v0.1 plan. This file enables that work; it doesn't
preempt it.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Integer, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Naming convention for indexes, constraints, and foreign keys.
#
# Without this, autogenerated names look like `ix_4f2c1a` and break Alembic
# autogenerate (it can't recognise an existing constraint to omit it). With
# this, names are deterministic and round-trip cleanly through migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Project-wide declarative base.

    Every ORM model in OpenSpine inherits from this class. It carries the
    shared metadata (with the naming convention above) so Alembic generates
    deterministic migration names.
    """

    metadata = metadata


# ---- Mixins ----------------------------------------------------------------
#
# Mixins use plain `mapped_column` with string ForeignKey references. The
# strings are resolved by SQLAlchemy at metadata-load time, so we don't need
# `@declared_attr` complexity to defer the resolution.


class _UUIDPrimaryKeyMixin:
    """Single-column UUID primary key.

    Per `data-model.md`, every business table has `id UUID PRIMARY KEY` with
    a server-side default of `gen_random_uuid()` (Postgres 13+ — built-in,
    no extension required).
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class _AuditColumnsMixin:
    """`created_at`, `created_by`, `updated_at`, `updated_by`, `version`.

    Per `data-model.md`. `created_*` are insert-only; `updated_*` and
    `version` are touched by a `BEFORE UPDATE` trigger that the migration
    accompanying the first concrete table installs once at first use.

    `created_by` and `updated_by` reference `id_principal(id)` via string
    FK; SQLAlchemy resolves the reference at metadata-load time, so we
    don't need to import the principal table here.

    The FK is `DEFERRABLE INITIALLY DEFERRED`. The bootstrap path inserts
    the first tenant + first principal in one transaction, where each row
    references the other before either is committed. Postgres only checks
    deferred constraints at COMMIT, breaking the chicken-and-egg cycle.
    No production code path relies on this; it is a one-time bootstrap
    affordance.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    created_by: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("id_principal.id", deferrable=True, initially="DEFERRED"),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_by: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("id_principal.id", deferrable=True, initially="DEFERRED"),
        nullable=False,
    )
    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        server_default=text("1"),
    )


class _TenantColumnMixin:
    """`tenant_id` foreign key + tenancy boundary marker.

    Every business table (excepting documented globals like `md_uom`,
    `md_currency`, `md_uom_conversion`) carries `tenant_id`. RLS policies
    reference this column.

    Like the audit-column FKs above, the FK to `id_tenant(id)` is
    `DEFERRABLE INITIALLY DEFERRED` so the bootstrap transaction can
    insert the first tenant and the first principal atomically.
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("id_tenant.id", deferrable=True, initially="DEFERRED"),
        nullable=False,
        index=True,
    )


# ---- Public mixin types ----------------------------------------------------


class AuditMixin(_UUIDPrimaryKeyMixin, _AuditColumnsMixin):
    """For tables that are tenant-global by design (UoM catalogues, currency).

    Carries the UUID PK and audit columns but **no** `tenant_id`.
    """


class BusinessTableMixin(_UUIDPrimaryKeyMixin, _TenantColumnMixin, _AuditColumnsMixin):
    """For every regular business table.

    UUID PK + tenant_id + audit columns. RLS policy is added in the
    accompanying migration; SQLAlchemy doesn't model row-level security
    directly.
    """


# ---- RLS helpers -----------------------------------------------------------


# Use set_config(name, value, is_local) — `SET LOCAL` is parser-level
# and does not accept bind parameters. set_config() is the function form.
# Third arg `true` makes it transaction-local, matching SET LOCAL semantics.
SET_TENANT_SQL = text("SELECT set_config('openspine.tenant_id', :tenant_id, true)")


def set_session_tenant(session: Any, tenant_id: str | uuid.UUID) -> None:
    """Set the per-session tenant id for RLS on the current transaction.

    Call once per request, before any tenant-scoped query, from the
    principal-context middleware. The value persists for the duration of
    the current transaction and is cleared on COMMIT/ROLLBACK.
    """
    session.execute(SET_TENANT_SQL, {"tenant_id": str(tenant_id)})


__all__ = [
    "NAMING_CONVENTION",
    "SET_TENANT_SQL",
    "AuditMixin",
    "Base",
    "BusinessTableMixin",
    "metadata",
    "set_session_tenant",
]
