"""identity core — id_* tables, audit trigger, RLS policies

Revision ID: 0002_identity_core
Revises: 0001_initial
Create Date: 2026-05-03

Lands the v0.1 §4.2 schema:

- ten `id_*` tables for tenancy, principals, credentials, sessions,
  tokens, federated identity, audit events
- one shared `_id_touch_updated_audit()` trigger function, attached to
  every table that carries `updated_at`/`version` (skips append-only
  `id_audit_event`)
- RLS enabled with `tenant_isolation` policy on every tenant-scoped
  identity table (skips global-registry `id_tenant`)

Hand-written rather than autogenerated. Alembic --autogenerate doesn't
know about RLS or trigger functions; treating those as "always custom DDL"
keeps the diff easy to read.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

revision: str = "0002_identity_core"
down_revision: str | Sequence[str] | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tables that get the BEFORE UPDATE audit trigger. Mirrors
# `openspine.identity.models.TABLES_WITH_UPDATE_TRIGGER` but kept as a
# literal so this migration is independent of Python-side imports.
_TRIGGER_TABLES: tuple[str, ...] = (
    "id_tenant",
    "id_tenant_setting",
    "id_principal",
    "id_human_profile",
    "id_agent_profile",
    "id_credential",
    "id_session",
    "id_token",
    "id_federated_identity",
)

# Tables that get tenant-isolation RLS. `id_tenant` deliberately omitted —
# it is the global registry; access is gated at the service layer.
_RLS_TABLES: tuple[str, ...] = (
    "id_tenant_setting",
    "id_principal",
    "id_human_profile",
    "id_agent_profile",
    "id_credential",
    "id_session",
    "id_token",
    "id_federated_identity",
    "id_audit_event",
)


def _audit_columns_no_pk(
    *, with_principal_fk: bool = True
) -> list[sa.Column[object]]:
    """The five audit columns shared by every BusinessTableMixin/AuditMixin
    table.

    `with_principal_fk=False` produces the columns WITHOUT the FK to
    `id_principal.id`. We use that for the two bootstrap tables
    (`id_tenant`, `id_principal`) where the FK target doesn't exist
    at create-table time. The FK is added back via ALTER TABLE after
    both tables exist (DEFERRABLE INITIALLY DEFERRED handles the
    runtime insert cycle separately).
    """
    cols: list[sa.Column[object]] = [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    ]
    if with_principal_fk:
        cols.append(
            sa.Column(
                "created_by",
                pg.UUID(as_uuid=True),
                sa.ForeignKey(
                    "id_principal.id", deferrable=True, initially="DEFERRED"
                ),
                nullable=False,
            )
        )
    else:
        cols.append(sa.Column("created_by", pg.UUID(as_uuid=True), nullable=False))
    cols.append(
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        )
    )
    if with_principal_fk:
        cols.append(
            sa.Column(
                "updated_by",
                pg.UUID(as_uuid=True),
                sa.ForeignKey(
                    "id_principal.id", deferrable=True, initially="DEFERRED"
                ),
                nullable=False,
            )
        )
    else:
        cols.append(sa.Column("updated_by", pg.UUID(as_uuid=True), nullable=False))
    cols.append(
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        )
    )
    return cols


def _id_pk() -> sa.Column[object]:
    return sa.Column(
        "id",
        pg.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )


def _tenant_fk(*, with_fk: bool = True) -> sa.Column[object]:
    """The standard `tenant_id` column. `with_fk=False` for the
    bootstrap principal table (FK added separately via ALTER)."""
    if with_fk:
        return sa.Column(
            "tenant_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_tenant.id", deferrable=True, initially="DEFERRED"),
            nullable=False,
            index=True,
        )
    return sa.Column(
        "tenant_id",
        pg.UUID(as_uuid=True),
        nullable=False,
        index=True,
    )


# ---------------------------------------------------------------------------


def upgrade() -> None:
    # 1. Trigger function — created once, attached per-table below.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION _id_touch_updated_audit() RETURNS trigger AS $$
        BEGIN
          NEW.updated_at := now();
          NEW.version := COALESCE(OLD.version, 0) + 1;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # 2. id_tenant — global registry, no RLS, no tenant_id column.
    #    Created without the FKs to id_principal because that table
    #    doesn't exist yet (cyclic dependency). FKs are added by
    #    ALTER TABLE below once id_principal exists.
    op.create_table(
        "id_tenant",
        _id_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'")),
        sa.Column(
            "deployment_metadata",
            pg.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        *_audit_columns_no_pk(with_principal_fk=False),
        sa.UniqueConstraint("slug", name="uq_id_tenant_slug"),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'archived')", name="ck_id_tenant_status"
        ),
    )

    # 3. id_principal — must come before id_tenant_setting (and the
    #    rest) because every other table's audit FK references
    #    id_principal. The table is created without the audit-author
    #    FKs (self-reference would resolve, but we use the same
    #    "no FK" path for consistency with id_tenant) and the FKs are
    #    added by ALTER TABLE below.
    op.create_table(
        "id_principal",
        _id_pk(),
        _tenant_fk(),  # id_tenant exists; tenant_id FK is fine here.
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'")),
        *_audit_columns_no_pk(with_principal_fk=False),
        sa.CheckConstraint(
            "kind IN ('human', 'agent', 'technical')", name="ck_id_principal_kind"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'deleted')", name="ck_id_principal_status"
        ),
        sa.UniqueConstraint("tenant_id", "username", name="uq_id_principal_username"),
    )

    # Now id_principal exists. Attach the audit-author FKs to id_tenant
    # and id_principal so the bootstrap insert path can rely on them.
    op.create_foreign_key(
        "fk_id_tenant_created_by_id_principal",
        "id_tenant",
        "id_principal",
        ["created_by"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_id_tenant_updated_by_id_principal",
        "id_tenant",
        "id_principal",
        ["updated_by"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_id_principal_created_by_id_principal",
        "id_principal",
        "id_principal",
        ["created_by"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_id_principal_updated_by_id_principal",
        "id_principal",
        "id_principal",
        ["updated_by"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )

    # 4. id_tenant_setting (and onward — both id_tenant and id_principal
    #    exist now, so audit FKs and tenant FKs work normally).
    op.create_table(
        "id_tenant_setting",
        _id_pk(),
        _tenant_fk(),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", pg.JSONB(), nullable=False),
        *_audit_columns_no_pk(),
        sa.UniqueConstraint("tenant_id", "key", name="uq_id_tenant_setting_key"),
    )
    op.create_index(
        "ix_id_principal_tenant_kind", "id_principal", ["tenant_id", "kind"]
    )

    # 5. id_human_profile
    op.create_table(
        "id_human_profile",
        _id_pk(),
        _tenant_fk(),
        sa.Column(
            "principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("locale", sa.Text(), nullable=False, server_default=sa.text("'en'")),
        sa.Column("time_zone", sa.Text(), nullable=False, server_default=sa.text("'UTC'")),
        sa.Column(
            "manager_principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="SET NULL"),
            nullable=True,
        ),
        *_audit_columns_no_pk(),
        sa.UniqueConstraint("principal_id", name="uq_id_human_profile_principal_id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_id_human_profile_email"),
    )
    op.create_index(
        "ix_id_human_profile_manager", "id_human_profile", ["manager_principal_id"]
    )

    # 6. id_agent_profile
    op.create_table(
        "id_agent_profile",
        _id_pk(),
        _tenant_fk(),
        sa.Column(
            "principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column(
            "provisioner_principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("constraint_summary", sa.Text(), nullable=True),
        *_audit_columns_no_pk(),
        sa.UniqueConstraint("principal_id", name="uq_id_agent_profile_principal_id"),
    )
    op.create_index(
        "ix_id_agent_profile_provisioner",
        "id_agent_profile",
        ["provisioner_principal_id"],
    )

    # 7. id_credential
    op.create_table(
        "id_credential",
        _id_pk(),
        _tenant_fk(),
        sa.Column(
            "principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("secret_hash", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'")),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        *_audit_columns_no_pk(),
        sa.CheckConstraint(
            "kind IN ('password', 'totp_secret', 'sso_federation', 'token_indirection')",
            name="ck_id_credential_kind",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'revoked')", name="ck_id_credential_status"
        ),
    )
    op.create_index(
        "ix_id_credential_principal_kind", "id_credential", ["principal_id", "kind"]
    )

    # 8. id_session
    op.create_table(
        "id_session",
        _id_pk(),
        _tenant_fk(),
        sa.Column(
            "principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("session_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'")),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        *_audit_columns_no_pk(),
        sa.UniqueConstraint("session_hash", name="uq_id_session_session_hash"),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'revoked')", name="ck_id_session_status"
        ),
    )
    op.create_index("ix_id_session_principal", "id_session", ["principal_id"])

    # 9. id_token
    op.create_table(
        "id_token",
        _id_pk(),
        _tenant_fk(),
        sa.Column(
            "principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("prefix", sa.String(length=32), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "scope", pg.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        sa.Column(
            "provisioner_principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "revoked_by_principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="RESTRICT"),
            nullable=True,
        ),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        *_audit_columns_no_pk(),
        sa.UniqueConstraint("secret_hash", name="uq_id_token_secret_hash"),
        sa.CheckConstraint(
            "kind IN ('user_api', 'agent', 'service')", name="ck_id_token_kind"
        ),
        sa.CheckConstraint(
            "kind <> 'agent' OR ("
            "expires_at IS NOT NULL"
            " AND provisioner_principal_id IS NOT NULL"
            " AND reason IS NOT NULL)",
            name="ck_id_token_agent_invariants",
        ),
    )
    op.create_index("ix_id_token_principal", "id_token", ["principal_id"])
    op.create_index(
        "ix_id_token_provisioner", "id_token", ["provisioner_principal_id"]
    )

    # 10. id_federated_identity
    op.create_table(
        "id_federated_identity",
        _id_pk(),
        _tenant_fk(),
        sa.Column(
            "principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("last_authenticated_at", sa.DateTime(timezone=True), nullable=True),
        *_audit_columns_no_pk(),
        sa.UniqueConstraint(
            "tenant_id", "issuer", "subject", name="uq_id_federated_identity_iss_sub"
        ),
    )
    op.create_index(
        "ix_id_federated_identity_principal", "id_federated_identity", ["principal_id"]
    )

    # 11. id_audit_event — append-only, no audit trigger, no version.
    op.create_table(
        "id_audit_event",
        _id_pk(),
        sa.Column(
            "tenant_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_tenant.id", deferrable=True, initially="DEFERRED"),
            nullable=True,
        ),
        sa.Column("trace_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "principal_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", deferrable=True, initially="DEFERRED"),
            nullable=True,
        ),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_kind", sa.Text(), nullable=True),
        sa.Column("target_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            pg.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "created_by",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("id_principal.id", deferrable=True, initially="DEFERRED"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "outcome IN ('success', 'failure')", name="ck_id_audit_event_outcome"
        ),
    )
    op.create_index(
        "ix_id_audit_event_tenant_action", "id_audit_event", ["tenant_id", "action"]
    )
    op.create_index("ix_id_audit_event_trace", "id_audit_event", ["trace_id"])
    op.create_index("ix_id_audit_event_created_at", "id_audit_event", ["created_at"])
    op.create_index("ix_id_audit_event_principal", "id_audit_event", ["principal_id"])

    # 12. Attach the BEFORE UPDATE trigger to every table that has
    #     updated_at + version. id_audit_event is excluded by design.
    for table in _TRIGGER_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER {table}_touch_updated_audit
              BEFORE UPDATE ON {table}
              FOR EACH ROW EXECUTE FUNCTION _id_touch_updated_audit();
            """
        )

    # 13. Enable RLS + the tenant_isolation policy on every tenant-scoped
    #     identity table. id_tenant is the registry; it has its own
    #     service-layer gate.
    for table in _RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = current_setting('openspine.tenant_id', true)::uuid);
            """
        )


def downgrade() -> None:
    # RLS policies + triggers drop with their tables; named explicitly here
    # for clarity in case a partial rollback is ever needed.
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
    for table in reversed(_TRIGGER_TABLES):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_touch_updated_audit ON {table};")

    op.drop_index("ix_id_audit_event_principal", table_name="id_audit_event")
    op.drop_index("ix_id_audit_event_created_at", table_name="id_audit_event")
    op.drop_index("ix_id_audit_event_trace", table_name="id_audit_event")
    op.drop_index("ix_id_audit_event_tenant_action", table_name="id_audit_event")
    op.drop_table("id_audit_event")

    op.drop_index("ix_id_federated_identity_principal", table_name="id_federated_identity")
    op.drop_table("id_federated_identity")

    op.drop_index("ix_id_token_provisioner", table_name="id_token")
    op.drop_index("ix_id_token_principal", table_name="id_token")
    op.drop_table("id_token")

    op.drop_index("ix_id_session_principal", table_name="id_session")
    op.drop_table("id_session")

    op.drop_index("ix_id_credential_principal_kind", table_name="id_credential")
    op.drop_table("id_credential")

    op.drop_index("ix_id_agent_profile_provisioner", table_name="id_agent_profile")
    op.drop_table("id_agent_profile")
    op.drop_index("ix_id_human_profile_manager", table_name="id_human_profile")
    op.drop_table("id_human_profile")

    op.drop_table("id_tenant_setting")

    # Break the cyclic FKs before dropping the tables.
    op.drop_constraint(
        "fk_id_principal_updated_by_id_principal", "id_principal", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_id_principal_created_by_id_principal", "id_principal", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_id_tenant_updated_by_id_principal", "id_tenant", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_id_tenant_created_by_id_principal", "id_tenant", type_="foreignkey"
    )

    op.drop_index("ix_id_principal_tenant_kind", table_name="id_principal")
    op.drop_table("id_principal")
    op.drop_table("id_tenant")

    op.execute("DROP FUNCTION IF EXISTS _id_touch_updated_audit();")
